# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: minimal
  theme_night: minimal
  font: native
  font_size: L

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Research and teaching website of Willi Mutschler'
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: 'Â© {year} Willi Mutschler. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: true
      share_alike: true
      allow_commercial: true

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '15:04'
  address_format: de

# Site features

features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - r
      - latex
      - matlab
  math:
    enable: true
  diagram:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/wmutschl/mutschler.eu'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
    #shape: square
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: mapnik
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  isotope:
    # Enable if you use the Portfolio widget or Publication filter
    enable: true
  academicons:
    enable: true